require 'plugins'
require 'options'
require 'ui'
require 'keybindings'
require 'mytelescope'
require 'mytreesitter'
-- require 'treesitter'
-- require 'statusline'
-- require 'completion'
-- require 'lsp'
